version: '3.8'

# Download the latest docker-compose.yml file from https://docker.surrealdb.com
# curl -sSf https://docker.surrealdb.com -o docker-compose.yml

services:
  surrealdb:
    image: 'surrealdb/surrealdb:v2'
    command: start --allow-all --bind=0.0.0.0:8000
    user: root
    environment:
      - SERVICE_FQDN_SURREALDB_8000
      - 'SURREAL_PATH=${SURREAL_PATH:-rocksdb://data/database.db}'
      - 'SURREAL_USER=${SERVICE_USER_ROOT}'
      - 'SURREAL_PASS=${SERVICE_PASSWORD_ROOT}'
      - 'SURREAL_EXPERIMENTAL_GRAPHQL=${ENABLE_GRAPHQL:-true}'
      - 'SURREAL_LOG=${SURREAL_LOG:-info}'
      - 'SURREAL_STRICT=${SURREAL_STRICT:-false}'
      - 'SURREAL_CLIENT_IP=${SURREAL_CLIENT_IP:-X-Forwarded-For}'
      - 'SURREAL_CAPS_ALLOW_GUESTS=${SURREAL_CAPS_ALLOW_GUESTS:-false}'
      - 'SURREAL_CAPS_ALLOW_SCRIPT=${SURREAL_CAPS_ALLOW_SCRIPT:-true}'
      - 'SURREAL_CAPS_ALLOW_NET=${SURREAL_CAPS_ALLOW_NET:-false}'
      - 'SURREAL_CAPS_DENY_FUNC=${SURREAL_CAPS_DENY_FUNC:-false}'
    volumes:
      - type: volume
        source: surrealdb
        target: /data
    ports:
      - "8000:8000"
    healthcheck:
      test:
        - CMD
        - /surreal
        - isready
      interval: 2s
      timeout: 10s
      retries: 10

volumes:
  surrealdb:
